Repository tonikasoft/fpsdk, pull requests merged in 2020-04, with the labels that each got.

#5 Fix compilation on Windows (#3)
  README.md
Labels: bug

#8 Implement plugin dispatcher (#4)
  Cargo.toml
  README.md
  src/cxx/generictransport.h
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
  src/lib.rs
  src/plugin.rs
Labels: enhancement

#7 Add install script on Windows (#1)
  install.win.bat
Labels: dev tools

#10 Add logger to the example (#2)
  Cargo.toml
  README.md
  examples/simple.rs
  src/host.rs
  src/lib.rs
Labels: dev tools, enhancement

#15 Example's log path on Windows (#14)
  README.md
Labels: documentation, windows

#12 Fix plugin dispatcher (#11)
  Cargo.toml
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
  src/lib.rs
  src/plugin.rs
Labels: bug

#18 Fix example's crash (#16)
  Cargo.toml
  examples/simple.rs
  src/cxx/wrapper.cpp
Labels: bug, windows

#19 Port flags to Rust (#13)
  src/lib.rs
Labels: enhancement

#30 Port event IDs to Rust (#21)
  src/host.rs
Labels: enhancement

#65 Port TFruityPlug->GetName (#24)
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/host.rs
  src/lib.rs
  src/plugin.rs
Labels: enhancement

#67 Port TFruityPlug->ProcessEvent (#25)
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
  src/lib.rs
  src/plugin.rs
Labels: enhancement

#68 Port TFruityPlug->NewTick (#33)
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/lib.rs
  src/plugin.rs
Labels: enhancement

#69 Port TFruityPlug->MIDITick (#34)
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/lib.rs
  src/plugin.rs
Labels: enhancement

#70 Port TFruityPlug->ProcessParam (#26)
  _clang-format
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
  src/lib.rs
  src/plugin.rs
Labels: enhancement

#71 Port TFruityPlug->Eff_Render (#27)
  .gitignore
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/lib.rs
  src/plugin.rs
Labels: enhancement

#72 Port TFruityPlug->Gen_Render (#28)
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/lib.rs
  src/plugin.rs
Labels: enhancement

#66 Port TFruityPlug->Idle_Public to Rust (#22)
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
  src/lib.rs
  src/plugin.rs
Labels: enhancement

#73 Port TFruityPlug->MIDIIn (#35)
  examples/simple.rs
  install.mac.sh
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/lib.rs
  src/plugin.rs
Labels: enhancement

#75 Port TFruityPlug->SaveRestoreState (#23)
  Cargo.toml
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/lib.rs
  src/plugin.rs
Labels: enhancement

#77 Fix memory leaks introduced by Box::into_raw (#76)
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/lib.rs
Labels: bug
