Repository tonikasoft/fpsdk, pull requests merged in 2020-05, with the labels that each got.

#78 Port voice related methods of TFruityPlug (#31)
  .gitignore
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/lib.rs
  src/plugin.rs
  src/voice.rs
Labels: enhancement

#79 Port TFruityPlug output voice methods (#37)
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/lib.rs
  src/plugin.rs
  src/voice.rs
Labels: enhancement

#80 Port TFruityPlugHost output voice methods (#63)
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
  src/lib.rs
  src/plugin.rs
  src/voice.rs
Labels: enhancement

#81 Port host voices methods (#43)
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
  src/plugin.rs
  src/voice.rs
Labels: enhancement

#82 Port TFruityPlugHost->Dispatcher (#40)
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
  src/lib.rs
  src/plugin.rs
  src/plugin/message.rs
  src/voice.rs
Labels: enhancement

#84 Port TFruityPlugHost->OnParamChanged (#41)
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
  src/lib.rs
Labels: enhancement

#87 Port TFruityPlugHost->OnHint (#42)
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
Labels: enhancement

#88 Port TFruityPlugHost MIDI out (#45)
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
  src/lib.rs
  src/plugin.rs
Labels: enhancement

#83 Port TFruityPlugHost PlugMsg methods (#51)
  examples/simple.rs
  install.win.bat
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
  src/lib.rs
  src/plugin.rs
Labels: enhancement

#91 Port TFruityPlugHost lock/unlock mix (#44)
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
Labels: enhancement

#93 Port TFruityPlugHost lock/unlock plugin methods (#61)
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
Labels: enhancement

#94 Port TFruityPlugHost suspend/resume output methods (#58)
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
Labels: enhancement

#92 Port TFruityPlugHost buffer getters (#62)
  README.md
  examples/simple.rs
  src/cxx/fp_cplug.cpp
  src/cxx/fp_cplug.h
  src/cxx/fp_extra.cpp
  src/cxx/fp_extra.h
  src/cxx/generictransport.h
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
  src/lib.rs
  src/voice.rs
Labels: enhancement

#96 Port TFruityPlugHost->PromptEdit (#57)
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
  src/host/prompt.rs
Labels: enhancement

#95 Port TFruityPlugHost->OnControllerChanged (#49)
  examples/simple.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
Labels: enhancement

#97 Decouple from cxx crate (#86)
  Cargo.toml
  build.rs
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/host.rs
  src/lib.rs
  src/plugin.rs
  src/plugin/message.rs
  src/voice.rs
Labels: enhancement

#98 Add CI/CD (#6)
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Cargo.toml
Labels: deployment, dev tools

#101 Test CI (#100)
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/cxx/wrapper.cpp
  src/cxx/wrapper.h
  src/plugin.rs
Labels: dev tools

#102 Change CI/CD names (#-)
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: dev tools

#104 Fix docs.rs build (#103)
  Cargo.toml
Labels: bug

#106 Fix build on linux (#105)
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/cxx/fp_def.h
  src/cxx/fp_plugclass.cpp
  src/cxx/fp_plugclass.h
Labels: bug

#107 Update version in Cargo.toml (#-)
  Cargo.toml
Labels: deployment

#109 Fix small mistakes in docs (#108)
  Cargo.toml
  src/host.rs
  src/lib.rs
  src/plugin.rs
Labels: documentation
